CREATE TABLE ENTREGA(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CLIENTE_ID BIGINT NOT NULL,
    TAXA DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DATA_PEDIDO DATETIME NOT NULL,
    DATA_FINALIZACAO DATETIME,

    DESTINATARIO_NOME VARCHAR(60) NOT NULL,
    DESTINATARIO_LOGRADOURO VARCHAR(255) NOT NULL,
    DESTINATARIO_NUMERO VARCHAR(30) NOT NULL,
    DESTINATARIO_COMPLEMENTO VARCHAR(60) NOT NULL,
    DESTINATARIO_BAIRRO VARCHAR(30) NOT NULL,

    PRIMARY KEY (ID)

);

ALTER TABLE ENTREGA ADD CONSTRAINT FK_ENTREGA_CLIENTE
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID);